github: [Codewithajoydas] 
patreon: joypatreon
open_collective: JS-PROJECTS
ko_fi: joykofi
community_bridge: JS-PROJECTS
liberapay: joylibera
issuehunt: joyissue
lfx_crowdfunding: JS-PROJECTS
polar: joypolar
buy_me_a_coffee: joycoffee
thanks_dev: joythanks
